### PR TITLE
Add coverity scan

### PR DESCRIPTION
**Pull request by KamilLepek**

### CODE REVIEW

**Review by awilczyns — DISMISSED** [review]

**Review by pwysock1-intel — APPROVED** [review]
I do approve these changes.

**Comment by KamilLepek** [comment]
I will leave it as an open PR (to test) for a while until I am certain to merge. Thanks for approves

**Review by soopel — DISMISSED** [review]
Approved

**Comment by KamilLepek** [comment]
Converted to draft PR to avoid unnecessary merge to not drain rate limiting of coverity scans

**Review by soopel — APPROVED** [review]
Approved

**Pull request merged**
