### PR TITLE
Private/mlinkiew/fixes

### PR DESCRIPTION
**Pull request by Mionsz**
[Dockerfiles adjustments to Trivy report](https://github.com/OpenVisualCloud/Media-Communications-Mesh/commit/6efbc9da566fb3192a2abfdf8e7a6e0e3dfd6aac) 

- exposed used port 8001 and 8002
- default user set to  mcm
- entrypoint, cmd and shell are now valid

[Linker settings changed to static](https://github.com/OpenVisualCloud/Media-Communications-Mesh/commit/d9f95e1e8bb8532ec027343903009f0c37f86b72) 

Statically link library with memif included makes dynamic linking issues not appear.
Added default link against LIB_BSD as it is used and not linked explicitally.

Changes default patch actions for ffmpeg-plugin
- Using 'apply' removed in favor of ' am --whitespaces=fix ', the new one physically applies a patch on a repository instread of uncommited changes.
- New approach does not require basic data to be fealed (name and e-mail), patch was modified to include commiter full data (as done in other pojects).
- Updated project version in FFmpeg MCM to reflect SDK version from tag.

[Changelog as requested by Cybura Lukasz added](https://github.com/OpenVisualCloud/Media-Communications-Mesh/pull/154/commits/d1dc1d9ca05ba0c7aa8fb874506973fee484bf94)

Missing changelog after a release was added as requested by Cybura Lukasz.

### CODE REVIEW

**Comment by Mionsz** [comment]
@ko80  fell free to merge or correct it if needed.

**Comment by ko80** [comment]
Since this doesn't touch the implementation of sample apps, SDK, FFmpeg plugin, nor media_proxy, it looks good to me.

**Review by ko80 — DISMISSED** [review]

**Review by soopel — APPROVED** [review]
Looks good to me

**Comment by Mionsz** [comment]
@ko80  @soopel  do not yet merge!

**Comment by Mionsz** [comment]
@ko80  @soopel please test it with the pre-release version of our internal project before merging. I was able to test inly this repo on baremetal and inside docker env

**Review by soopel — APPROVED** [review]
Looks good from my side. If tests pass I'm ok with merge.

**Review by lcybura — CHANGES_REQUESTED** [review]
please remove internal Jira IDs

**Review by ko80 — CHANGES_REQUESTED** [review]
I can't approve that because a simple test with running an MCM JPEG XS pipeline with media proxies running in containers fails. The traffic seems to pass between media proxies but the Rx FFmpeg gets only from ~10 to 30 frames and then stops. The Rx media proxy container exits. Dmesg output
```
[3276057.328279] traps: media_proxy[1157208] general protection fault ip:7fb29d119898 sp:7fb1c97f8850 error:0 in libc.so.6[7fb29d119000+195000]
```

**Pull request closed without merging**
