### PR TITLE
Change library and k8s resource names

### PR DESCRIPTION
**Pull request by ko80**
* Change library names
* Update k8s resource names

### CODE REVIEW

**Review by pwysock1-intel — APPROVED** [review]
I do approve these changes.

**Review by Mionsz — COMMENTED** [review]
As we talked - the deployment folder labels can also be refactored to meet new naming convention standards.

**Review by Mionsz — APPROVED** [review]
Great work. Now all is ok. LGTM

**Review by pwysock1-intel — APPROVED** [review]
Approved.

**Pull request merged**
